// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtUEX15VBjXkjFezIB-ZSGQ5J3nM-K1qc',
    appId: '1:1031318034346:web:9ef5333f3dd034753c7dd3',
    messagingSenderId: '1031318034346',
    projectId: 'e-commerce-92163',
    authDomain: 'e-commerce-92163.firebaseapp.com',
    databaseURL: 'https://e-commerce-92163-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-92163.firebasestorage.app',
    measurementId: 'G-BDGNPTD2R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPOy3HD0HySLO4T29zMeaP_fHvaOfw3KU',
    appId: '1:1031318034346:android:f5c856eb258749683c7dd3',
    messagingSenderId: '1031318034346',
    projectId: 'e-commerce-92163',
    authDomain: 'e-commerce-92163.firebaseapp.com',
    databaseURL: 'https://e-commerce-92163-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-92163.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoPiA0MNIaS2zigfakhCUr4kiqw3Y2gfQ',
    appId: '1:1031318034346:ios:9c2875b03fe9aa0a3c7dd3',
    messagingSenderId: '1031318034346',
    projectId: 'e-commerce-92163',
    authDomain: 'e-commerce-92163.firebaseapp.com',
    databaseURL: 'https://e-commerce-92163-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-92163.firebasestorage.app',
    iosBundleId: 'com.example.nutratrust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoPiA0MNIaS2zigfakhCUr4kiqw3Y2gfQ',
    appId: '1:1031318034346:ios:9c2875b03fe9aa0a3c7dd3',
    messagingSenderId: '1031318034346',
    projectId: 'e-commerce-92163',
    authDomain: 'e-commerce-92163.firebaseapp.com',
    databaseURL: 'https://e-commerce-92163-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-92163.firebasestorage.app',
    iosBundleId: 'com.example.nutratrust',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtUEX15VBjXkjFezIB-ZSGQ5J3nM-K1qc',
    appId: '1:1031318034346:web:a29c6f8a46c841933c7dd3',
    messagingSenderId: '1031318034346',
    projectId: 'e-commerce-92163',
    authDomain: 'e-commerce-92163.firebaseapp.com',
    databaseURL: 'https://e-commerce-92163-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-92163.firebasestorage.app',
    measurementId: 'G-LTGEKK8PEC',
  );
}
